### PR TITLE
Fix: FreeBSD build

### LINKED ISSUE #439: [ bug ] mismatched types
```sh
error[E0308]: mismatched types                                                                                                                                                                                
   --> /tmp/tmp.1vrLGmLkbB/work/rustic-f0ddb47/cargo-crates/rustic_core-0.9.0/src/backend/local_destination.rs:666:65                                                                                         
    |                                                                                                                                                                                                         
666 |                 mknod(&filename, SFlag::S_IFBLK, Mode::empty(), device)                                                                                                                                 
    |                 ----- arguments to this function are incorrect  ^^^^^^ expected `u64`, found `u32`                                                                                                      
    |                                                                                                                                                                                                         
note: function defined here                                                                                                                                                                                   
   --> /tmp/tmp.1vrLGmLkbB/work/rustic-f0ddb47/cargo-crates/nix-0.30.1/src/sys/stat.rs:155:8                                                                                                                  
    |                                                                                                                                                                                                         
155 | pub fn mknod<P: ?Sized + NixPath>(                                                                                                                                                                      
    |        ^^^^^                                                                                                                                                                                            
help: you can convert a `u32` to a `u64`                                                                                                                                                                      
    |                                                                                                                                                                                                         
666 |                 mknod(&filename, SFlag::S_IFBLK, Mode::empty(), device.into())                                                                                                                          
    |                                                                       +++++++                                                                                                                           

error[E0308]: mismatched types
   --> /tmp/tmp.1vrLGmLkbB/work/rustic-f0ddb47/cargo-crates/rustic_core-0.9.0/src/backend/local_destination.rs:692:65
    |
692 |                 mknod(&filename, SFlag::S_IFCHR, Mode::empty(), device)
    |                 ----- arguments to this function are incorrect  ^^^^^^ expected `u64`, found `u32`
    |
note: function defined here
   --> /tmp/tmp.1vrLGmLkbB/work/rustic-f0ddb47/cargo-crates/nix-0.30.1/src/sys/stat.rs:155:8
    |
155 | pub fn mknod<P: ?Sized + NixPath>(
    |        ^^^^^
help: you can convert a `u32` to a `u64`
    |
692 |                 mknod(&filename, SFlag::S_IFCHR, Mode::empty(), device.into())
    |                                                                       +++++++
```

commit: f0ddb47
cargo `1.93.0-nightly` 
OS: `FreeBSD 14`

### PR DESCRIPTION
**Pull request by yonas**
Fixes #439

### CODE REVIEW

**Comment by yonas** [comment]
@aawsome Thanks, I've update the PR and run `cargo fmt` on it.

File: crates/core/src/backend/local_destination.rs [hunk 1]
```diff
@@ -661,23 +657,11 @@ impl LocalDestination {
...
                     }
                 })?;
-                #[cfg(target_os = "freebsd")]
-                let device = u32::try_from(*device).map_err(|err| {
-                    LocalDestinationErrorKind::DeviceIdConversionFailed {
-                        target: "u32".to_string(),
-                        device: *device,
-                        source: err,
-                    }
-                })?;
```
Comment (aawsome) [inline crates/core/src/backend/local_destination.rs]: I wonder why FreeBSD was `u32` and now changed to `u64`...

**Review by aawsome — APPROVED** [review]
LGTM! Thanks a lot @yonas!
